# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'UIDynamics' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'SnapKit', '~> 5.6.0'
  pod 'Then', '3.0.0'
  # Pods for UIDynamics

  target 'UIDynamicsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'UIDynamicsUITests' do
    # Pods for testing
  end

end
